### ISSUE TITLE
Only code opening in max?

### ISSUE THREAD

**Issue by CarloCattano** [CreativeInquiry/FaceOSC-Templates#7]
Hi , i open the max patch in max 7.1 and i only get code.
When i try to paste it into a new patch it doesnt allow to "paste" ?

**Comment by driftnote** [comment]
had the same problem but when you download the zip file by clicking "clone or download" the patch works

**Comment by danzeeeman** [comment]
the max patch is very very very very very old

**Comment by driftnote** [comment]
and in very very very very good working conditions. currently using it to do an AR installation

**Comment by danomatika** [comment]
Closing do to inactivity.
